FROM maven:3.6-jdk-8-alpine AS builder
WORKDIR /app
COPY pom.xml .
RUN mvn -e -B dependency:resolve
COPY src ./src
RUN mvn -e -B package
RUN ls -rtl /app/target


FROM openjdk:8-jre-alpine
COPY --from=builder /app/target/<artifactId in pom.xml>-<version in pom.xml>.jar /
CMD ["java", "-jar", "/<artifactId in pom.xml>-<version in pom.xml>.jar"]
